#In production server, for overriding this profiles config, gragle should run with : bootRun -Dspring.profiles.active=production
spring:
  profiles:
    active: development

#Production env default config
---
spring:
  profiles: production
  data:
      cassandra:
        port: 9042
        keyspace-name: kobito_dev
        contact-points: 35.190.226.237
server:
  address: 0.0.0.0
  port: 8083
#Logging configure
logging:
  config: 'classpath:log4j2.yml'
kobito:
  config:
    twitter:
      importTweetHistory: false
#Development env default config
---
spring:
  profiles: development
  data:
      cassandra:
        port: 9042
        keyspace-name: kobito_dev
        contact-points: 35.190.226.237
server:
  address: 0.0.0.0
  port: 9093
#Logging configure
logging:
  config: 'classpath:log4j2_dev.yml'
#kobito:
#  config:
#    twitter:
#      importTweetHistory: true
#      twitterTraders: SingalFactory,MAPSInvestments
#      tradingWords: buy,Buy,BUY,sell,Sell,SELL,Loss,loss,LOSS,Profit,profit,PROFIT,Close,close,CLOSE,Open,pips
