language: java
jdk: oraclejdk8
sudo: requiet
env:
  global:
    - JAVA_OPTS=-Xmx512m
cache:
  directories:
    - $HOME/.gradle
before_install:
 - chmod +x gradlew
 - ./gradlew assemble
 - ./gradlew check
