#In production server, for overriding this profiles config, gragle should run with : bootRun -Dspring.profiles.active=production
spring:
  profiles:
    active: development

#Production env default config
---
spring:
  profiles: production
  data:
    cassandra:
      port: 9042
      keyspace-name: mykeyspace
      contact-points: localhost
  social:
      twitter:
        appId: WkEM9cJR22UoTpPENqEYycUXy
        appSecret: awJz9ZSGACLahOlXE1Q6hLSrmeNYGCrCCRNPCjFOA91lmtIcqa
        accessToken: 14710799-Ew6GMveAcrkX9akyS0QPpIvWo5JCDxXC1AE42KcaQ
        accessTokenSecret: wsSvW0AA6oNWEE7PkLtpmVV9hS1V0L823Cx8H3TP6zyMX
server:
  address: localhost
  port: 8081
#Logging configure
logging:
  config: 'classpath:log4j2.yml'
kobito:
  config:
    twitter:
      importTweetHistory: false
#Development env default config
---
spring:
  profiles: development
  data:
    cassandra:
      port: 9042
      keyspace-name: mykeyspace
      contact-points: localhost
  social:
    twitter:
      appId: WkEM9cJR22UoTpPENqEYycUXy
      appSecret: awJz9ZSGACLahOlXE1Q6hLSrmeNYGCrCCRNPCjFOA91lmtIcqa
      accessToken: 14710799-Ew6GMveAcrkX9akyS0QPpIvWo5JCDxXC1AE42KcaQ
      accessTokenSecret: wsSvW0AA6oNWEE7PkLtpmVV9hS1V0L823Cx8H3TP6zyMX
server:
  address: localhost
  port: 9091
#Logging configure
logging:
  config: 'classpath:log4j2_dev.yml'
kobito:
  config:
    twitter:
      importTweetHistory: true
